export interface Project {
  id: string;
  slug: string;
  name: string;
  client: string;
  location: string;
  workingArea: string;
  totalCost: string;
  description: string;
  images: string[];
  serviceType:
    | "Interior Design & Construction"
    | "Building Design Consultancy"
    | "Building Construction"
    | "Customized Furniture & Lighting"
    | "Building Material Supply";
}

// This would typically come from a database, but for now we'll hardcode the projects
export const projects: Project[] = [
  {
    id: "1",
    slug: "avani",
    name: "Avani",
    client: "Dr. Rita Das",
    location: "Epic Saleh Cielo",
    workingArea: "1600 sq. ft.",
    totalCost: "₹24 lakh",
    serviceType: "Interior Design & Construction",
    description:
      'The project "Avani" was designed with a wooden and green color theme to create a nature-inspired atmosphere. Earthy tones, wooden accents, and lush greenery were incorporated to evoke a calming and organic feel. The space was carefully crafted to bring a touch of nature indoors, blending modern design with natural elements. Additionally, we handcrafted the lighting fixtures, along with a customized sofa set and dining table, to perfectly match the overall aesthetic and functionality of the space.',
    images: [
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-20.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-24.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-8.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-21.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-9.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-22.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-14.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-1.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-13.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-15.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-2.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-3.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-4.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-5.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-6.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-7.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-10.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-11.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-12.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-16.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-17.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-18.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-19.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-23.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-25.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-26.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/avani-27.jpg",
    ],
  },
  {
    id: "2",
    slug: "mrinmoyi",
    name: "মৃন্ময়ী",
    client: "Mr. Dipankar",
    location: "Noapara, Chattogram",
    workingArea: "1200 SFT",
    totalCost: "24 Lakh BDT",
    serviceType: "Building Construction",
    description:
      "Nestled amidst the lush greenery of Noapara, মৃন্ময়ী is a harmonious fusion of contemporary elegance and timeless charm. Designed to embrace natural light and ventilation, its distinctive bay windows, sloped entrance porch, and earthy tones create a warm and inviting ambiance. Every corner of this home reflects our commitment to craftsmanship, functionality, and aesthetic appeal. A true sanctuary built with passion by Ecoscape Design and Construction.",
    images: [
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/mrinmoyi-1.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/mrinmoyi-2.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/mrinmoyi-3.jpg",
    ],
  },
  {
    id: "3",
    slug: "srinibash-residence",
    name: "Srinibash Residence",
    client: "Joyonta Banik",
    location: "MTC Tower, Rayer Bazar High School",
    workingArea: "3200 sft",
    totalCost: "36 Lakhs",
    serviceType: "Interior Design & Construction",
    description:
      "The Srinibash Residence is a luxury project that blends elegance with modern design. High-end lighting and marvel texture finishes create a sophisticated ambiance, while the wall-hanging divan with a stone base adds a unique architectural touch. Every detail of this project was carefully crafted to deliver an exceptional and timeless living experience.",
    images: [
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-27.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-14.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-13.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-12.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-3.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-6.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-7.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-1.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-24.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-25.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-30.webp",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-18.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-19.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-26.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-15.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-4.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-29.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-5.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-9.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-11.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-16.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-17.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-2.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-20.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-21.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-22.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-23.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-8.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/srinibash-28.jpg",
    ],
  },
  {
    id: "4",
    slug: "lambent",
    name: "Lambent",
    client: "Shapan Chowdhury",
    location: "Cement Crossing, Chattagram",
    workingArea: "600 sq. ft.",
    totalCost: "₹8 lakh",
    serviceType: "Interior Design & Construction",
    description:
      'The project "Lambent" was designed with a focus on unique ceiling patterns and innovative lighting. The space featured a striking onyx wall with hidden lighting from the back, creating a sophisticated effect. To enhance the design, the DB box was cleverly hidden behind a decorative wall panel, complete with integrated lighting. The overall design combined modern elegance with practical features, offering a refined and contemporary atmosphere.',
    images: [
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/lambent-1.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/lambent-2.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/lambent-3.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/lambent-4.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/lambent-5.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/lambent-6.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/lambent-7.jpg",
    ],
  },
  {
    id: "5",
    slug: "noah",
    name: "Noah",
    client: "Mr. Shimul",
    location: "Jamalkhan, Airbell, Chattogram",
    workingArea: "3200 SFT",
    totalCost: "42 Lakh BDT",
    serviceType: "Interior Design & Construction",
    description:
      "Crafted with precision and tailored to the client's vision, Noah is a seamless blend of functionality and refined aesthetics. The highlight of this interior project is its unique entry ceiling, designed to create a striking first impression while complementing the overall ambiance. Every element, from material selection to spatial arrangement, reflects a balance between elegance and practicality. A bespoke interior transformation by Ecoscape Design and Construction, where client aspirations meet artistic innovation.",
    images: [
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-1.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-2.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-3.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-4.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-5.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-6.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-7.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-8.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-9.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-10.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-11.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-12.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-13.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-14.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-15.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-16.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-17.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-18.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-19.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-20.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-21.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-22.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-23.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-24.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/noah-25.jpg",
    ],
  },
  {
    id: "6",
    slug: "purnata",
    name: "Purnata",
    client: "Nipun Deb",
    location: "Jamal Khan, Azad Bhaban, 3rd floor",
    workingArea: "700 SFT",
    totalCost: "6 Lakh BDT",
    serviceType: "Interior Design & Construction",
    description:
      "Purnota is an interior design project inspired by the deep connection to our roots—an ode to the simplicity and beauty of nature and village life. The space blends earthy elements like terracotta and intricate Alpona motifs, celebrating traditional craftsmanship. Handcrafted lighting and bamboo features emphasize sustainability while creating a warm, intimate atmosphere. Every design choice, from textures to materials, reflects the spirit of origin, grounding the space in both culture and nature. Purnota is a return to wholeness—where tradition meets modernity to create an environment that feels timeless, authentic, and rooted in the earth.",
    images: [
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/purnata-1.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/purnata-2.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/purnata-3.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/purnata-4.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/purnata-5.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/purnata-6.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/purnata-7.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/purnata-8.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/purnata-9.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/purnata-10.jpg",
    ],
  },
  {
    id: "7",
    slug: "amader-bari",
    name: "Amader Bari",
    client: "Mrs. Riya",
    location: "AK Khan , Amader Bari",
    workingArea: "1400 SFT",
    totalCost: "11 Lakh BDT",
    serviceType: "Interior Design & Construction",
    description:
      "In the 'Amader Bari' project, the 'Excellence in Elegance' concept was brought to life through a refined color palette of neutral tones, complemented by luxurious materials like marble, velvet, and polished wood. Carefully selected furniture pieces, elegant lighting, and curated artwork created a harmonious balance between sophistication and comfort. The design focused on creating an inviting yet opulent atmosphere, with each detail thoughtfully crafted to enhance both the beauty and functionality of the space.",
    images: [
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/amader+bari-1.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/amader+bari-2.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/amader+bari-3.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/amader+bari-4.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/amader+bari-5.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/amader+bari-6.jpg",
    ],
  },
  {
    id: "8",
    slug: "vinz",
    name: "VINZ",
    client: "Sanjoy Dev",
    location: "Halishahar, A block, Bus stand",
    workingArea: "90 SFT",
    totalCost: "1.4 Lakh BDT",
    serviceType: "Interior Design & Construction",
    description:
      "Modern elegance meets timeless comfort — discover the refined interiors of VINZ, where every detail tells a story of sophistication and style.",
    images: [
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Vinz-1.webp",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Vinz-2.webp",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Vinz-3.webp",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Vinz-4.webp",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Vinz-5.webp",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Vinz-6.webp",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Vinz-7.webp",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Vinz-8.webp",
    ],
  },
  {
    id: "9",
    slug: "equity-falguni-c-10",
    name: "Equity Falguni, C-10",
    client: "Pran Gopal",
    location: "Enayet Bazar, Chattogram",
    workingArea: "1100 SFT",
    totalCost: "8 Lakh BDT",
    serviceType: "Interior Design & Construction",
    description:
      "A refined symphony of black, gold, and white, this interior weaves together bold contrasts and graceful elegance. Crisp white walls offer a serene backdrop, allowing rich black elements and warm golden accents to take center stage. The result is a space that feels both grounded and luminous—where luxury meets restraint. Thoughtfully selected textures, sculptural lighting, and clean-lined furniture contribute to an atmosphere of timeless sophistication. With each detail carefully composed, this design by Ecoscape Design and Construction is a celebration of modern glamour, crafted for those who appreciate quiet opulence and impeccable balance.",
    images: [
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Equity+falguni-1.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Equity+falguni-2.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Equity+falguni-3.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Equity+falguni-4.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Equity+falguni-5.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Equity+falguni-6.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Equity+falguni-7.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Equity+falguni-8.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Equity+falguni-9.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Equity+falguni-10.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Equity+falguni-11.jpg",
    ],
  },
  {
    id: "10",
    slug: "green-bird-gec",
    name: "Green Bird, GEC",
    client: "Dr. Sayed Shafiul Islam",
    location: "Enayet Bazar, Chattogram",
    workingArea: "1800 SFT",
    totalCost: "22 Lakh BDT",
    serviceType: "Interior Design & Construction",
    description:
      "Tucked away in the tranquil surroundings of Green Bird, this thoughtfully designed residence is a seamless blend of modern sensibility and organic warmth. Rooted in the ethos of sustainable living, the home features open-plan layouts, wide balconies, and a palette inspired by nature—soft greens, warm woods, and clean lines. Designed to maximize airflow and natural light, each element speaks to a conscious balance between form and function.",
    images: [
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird-1.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird-2.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird-3.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird-4.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird-5.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird-6.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird -7.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird-8.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird-9.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird -10.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird-11.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird -13.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird-14.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird-15.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/grenn+bird-16.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird-17.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird-18.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird-19.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird-20.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird-21.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird-22.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird-23.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird-24.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/green+bird-25.jpg",
    ],
  },
  {
    id: "11",
    slug: "jasper",
    name: "Jasper",
    client: "Mr. Polash",
    location: "Jamalkhan Airbell Building",
    workingArea: "1400 SFT",
    totalCost: "14 Lakh BDT",
    serviceType: "Interior Design & Construction",
    description:
      "Project 'Jasper' is a warm, minimalist interior design concept focused on creating a cozy and inviting space that instantly feels like home. Rooted in simplicity, natural textures, and soft, earthy tones, Jasper emphasizes comfort without clutter. The design blends functional furniture with personal touches—like warm lighting, layered textiles, and curated decor—to foster a sense of calm and belonging. Whether it's a small apartment or a family home, Jasper is about making every space feel lived-in, loved, and authentically yours.",
    images: [
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-1.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-2.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-3.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-4.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-5.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-6.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-7.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-8.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-9.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-10.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-11.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-12.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-13.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-14.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-15.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-16.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-17.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-18.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-19.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-20.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-21.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/jasper-22.jpg",
    ],
  },
  {
    id: "12",
    slug: "liebestraum",
    name: "Liebestraum",
    client: "Mr. Tokon",
    location: "Rangpur, Palpara",
    workingArea: "1800 SFT",
    totalCost: "16 Lakh BDT",
    serviceType: "Interior Design & Construction",
    description:
      "Liebestraum is an interior design concept focused on creating a harmonious and serene environment that balances sophistication with comfort. The design features a soft color palette of muted tones like warm beiges, soft grays, and subtle greens, complemented by natural materials such as wood, stone, and marble. Furniture pieces with clean lines and organic shapes are paired with luxurious fabrics like velvet and linen to provide a tactile, elevated experience. Soft, ambient lighting, minimalistic decor, and carefully chosen artwork complete the space, making it a peaceful and refined retreat.",
    images: [
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/liebestraum-1.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/liebestraum-2.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/liebestraum-3.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/liebestraum-4.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/liebestraum-5.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/liebestraum-6.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/liebestraum-7.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/liebestraum-8.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/liebestraum-9.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/liebestraum-10.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/liebestraum-11.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/liebestraum-12.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/liebestraum-13.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/liebestraum-14.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/liebestraum-15.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/liebestraum-16.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/liebestraum-17.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/liebestraum-18.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/liebestraum-19.jpg",
    ],
  },
  {
    id: "13",
    slug: "natures-sheen",
    name: "Nature's Sheen",
    client: "Mr. Kanchan",
    location: "Kholifapotti, anderkilla",
    workingArea: "1100 SFT",
    totalCost: "6 Lakh BDT",
    serviceType: "Interior Design & Construction",
    description:
      "'Nature's Sheen' focuses on the timeless elegance of wood, bringing warmth and sophistication through rich, natural textures. The design emphasizes the beauty of raw, untreated wood, with intricate grain patterns showcased in furniture, flooring, and wall features. Soft metallic accents subtly complement the wood’s rustic charm, adding a hint of refined luxury. The result is a serene, yet striking space that evokes the quiet strength and graceful sheen of nature, offering a sanctuary of warmth and tactile beauty",
    images: [
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Nature_s+shean-1.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Nature_s+shean-2.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Nature_s+shean-3.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Nature_s+shean-4.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Nature_s+shean-5.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/Nature_s+shean-6.jpg",
    ],
  },
  // new project
  {
    id: "14",
    slug: "bandarban-duplex",
    name: "Bandarban Duplex",
    client: "Mrs. Benazir Jahangir",
    location: "Bandarban",
    workingArea: "2100 SFT",
    totalCost: "",
    serviceType: "Building Construction",
    description:
      "A modern duplex designed to offer two self-contained residential units within a single structure. Each unit features private entrances, contemporary finishes, and efficient layouts, ideal for families or individuals seeking comfort, privacy, and urban convenience.",
    images: [
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/bandarban-duplex-1.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/bandarban-duplex-2.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/bandarban-duplex-3.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/bandarban-duplex-4.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/bandarban-duplex-5.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/bandarban-duplex-6.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/bandarban-duplex-7.jpg",
    ],
  },
  {
    id: "15",
    slug: "rangpur-5-storied-building",
    name: "Rangpur 5-storied Building",
    client: "Mr. Tokon",
    location: "Rangpur",
    workingArea: "1100 SFT",
    totalCost: "1,10,00,000 BDT",
    serviceType: "Building Construction",
    description:
      "A constructed 5-storied residential building is a completed housing structure with five floors designed exclusively for residential use. It typically includes multiple apartments or housing units on each floor, along with essential amenities such as staircases, elevators, water supply, electrical systems, and safety features.",
    images: [
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/rangpur-1.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/rangpur-2.jpg",
    ],
  },
  {
    id: "16",
    slug: "satkaniya-6-storied-building",
    name: "Satkaniya 6-storied Building",
    client: "Mr. Abul Kashem",
    location: "Satkaniya",
    workingArea: "4800 SFT",
    totalCost: "",
    serviceType: "Building Construction",
    description:
      "This proposed six-storied building is designed to accommodate four residential units on each upper floor, offering a total of ten well-planned apartments. The ground floor is dedicated to commercial use, featuring several retail stores to serve both residents and the surrounding community. The building combines functionality with modern aesthetics, aiming to create a vibrant mixed-use development that enhances urban living.",
    images: [
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/satkaniya-1.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/satkaniya-2.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/satkaniya-3.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/satkaniya-4.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/satkaniya-5.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/satkaniya-6.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/satkaniya-7.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/satkaniya-8.jpg",
    ],
  },
  {
    id: "17",
    slug: "teribazar-8-storied-building",
    name: "Teribazar 8-storied Building",
    client: "Mr. Uttam",
    location: "Teribazar",
    workingArea: "1600 SFT",
    totalCost: "",
    serviceType: "Building Construction",
    description:
      "An 8-story residential building with a unique design is currently under construction in Teribazar. This innovative structure is set to offer modern living spaces, combining style and functionality to create a distinctive residential landmark in the area.",
    images: [
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/teribazar-1.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/teribazar-2.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/teribazar-3.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/teribazar-4.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/teribazar-5.jpg",
      "https://ecoscapebd-assets.s3.ap-south-1.amazonaws.com/teribazar-6.jpg",
    ],
  },
];

export async function getAllProjects(): Promise<Project[]> {
  // In a real application, you would fetch this from a database or API
  return projects;
}

export async function getProjectBySlug(slug: string): Promise<Project | null> {
  // In a real application, you would fetch this from a database or API
  const project = projects.find((p) => p.slug === slug);
  return project || null;
}

export async function getAllProjectSlugs(): Promise<string[]> {
  // In a real application, you would fetch this from a database or API
  return projects.map((project) => project.slug);
}
